// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0xqZaFVHWTKyR9WBdW2rHKfGwHgbSPkw',
    appId: '1:741427068413:web:dfcd6b766c2bd1066aed94',
    messagingSenderId: '741427068413',
    projectId: 'e-commerce-eced2',
    authDomain: 'e-commerce-eced2.firebaseapp.com',
    storageBucket: 'e-commerce-eced2.appspot.com',
    measurementId: 'G-D43CJ4XCE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX-Z1NyhMOqS5KKwkKPBkSKEXd7Ln7Vxg',
    appId: '1:741427068413:android:8f6a96f918c277d66aed94',
    messagingSenderId: '741427068413',
    projectId: 'e-commerce-eced2',
    storageBucket: 'e-commerce-eced2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnc3UcXj58iPb2zrw36YaLqwTYIakdVR0',
    appId: '1:741427068413:ios:8db9553e5a0d0bbc6aed94',
    messagingSenderId: '741427068413',
    projectId: 'e-commerce-eced2',
    storageBucket: 'e-commerce-eced2.appspot.com',
    iosBundleId: 'com.example.flutterCourseAug23Session9Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnc3UcXj58iPb2zrw36YaLqwTYIakdVR0',
    appId: '1:741427068413:ios:5ce3c8bd8b4533606aed94',
    messagingSenderId: '741427068413',
    projectId: 'e-commerce-eced2',
    storageBucket: 'e-commerce-eced2.appspot.com',
    iosBundleId: 'com.example.flutterCourseAug23Session9Firebase.RunnerTests',
  );
}
